version: '3'
services:
  web:
    image: citypay/magento2:admin
    #phpdbg
    container_name: web
    restart: "no"
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/magento
      - PHP_DATE_TIMEZONE=EST
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
      - PHP_EXTENSION_DEBUG=1
    ports:
      - "80:80"
      - "9000:9000"
    networks:
      - magentoworld
    volumes:
#      - C:\Users\marti\IdeaProjects\citypay-paylink-magento\files\etc:/var/www/html/magento/app/etc
#      - C:\Users\marti\IdeaProjects\citypay-paylink-magento\src\SamplePaymentGateway:/var/www/html/magento/app/code/Magento/SamplePaymentGateway
#      - C:\Users\marti\IdeaProjects\citypay-paylink-magento\src\CityPayPaylink:/var/www/html/magento/app/code/Magento/CityPayPaylink
#      - ./files/generated:/var/www/html/magento/generated
      -  magento2generated:/var/www/html/magento/generated
      - ./files/etc:/var/www/html/magento/app/etc
      - ./src/Paylink:/var/www/html/magento/app/code/CityPay/Paylink
#      - ./src/sample-module-payment-gateway:/var/www/html/magento/app/code/Magento/sample-module-payment-gateway
#      - ./src/sample-module-servicecontract-new:/var/www/html/magento/app/code/Magento/sample-module-servicecontract-new
#      - ./src/CityPayPaylink:/var/www/html/magento/app/code/Magento/CityPayPaylink
      - ./src/phptest:/var/www/html/phptest
      - ./src/25-xdebug.ini:/etc/php/7.2/cli/conf.d/25-xdebug.ini
      - ./src/25-xdebug.ini:/etc/php/7.2/apache2/conf.d/25-xdebug.ini
 #     - ./src/php.ini:/etc/php/7.2/cli/php2.ini

    links:
      - mysql
    command:  /bin/bash
    stdin_open: true
    tty: true
  mysql:
    image: mariadb:10
    container_name: mysql
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
    networks:
      - magentoworld
    volumes:
     # - C:\Users\marti\IdeaProjects\citypay-paylink-magento\data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
networks:
  magentoworld:
    driver: bridge

volumes:
  magento2generated: