version: '3'
services:
  web:
    image: citypay/magento2:latest
    container_name: web
    restart: always
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/magento
      - PHP_DATE_TIMEZONE=EST
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
    ports:
      - "80:80"
    networks:
      - magentoworld
    volumes:
      - ./src/SamplePaymentGateway:/var/www/html/magento/app/code/Magento/SamplePaymentGateway
      - ./src/CityPayPaylink:/var/www/html/magento/app/code/Magento/CityPayPaylink
    links:
      - mysql
  mysql:
    image: mariadb:10
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
    networks:
      - magentoworld
    volumes:
      - ./data:/var/lib/mysql
networks:
  magentoworld:
    driver: bridge