version: '3'
services:
  mailhog:
    container_name: citypay-magento-mail
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - magentoworld
  web:
    image: citypay/magento2:latest
    container_name: citypay-magento-web
    restart: "no"
    env_file: ".env"
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/magento
      - PHP_DATE_TIMEZONE=GMT
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - MAGENTO_REPO_USERNAME=${MAGENTO_REPO_USERNAME}
      - MAGENTO_REPO_PASSWORD=${MAGENTO_REPO_PASSWORD}
    ports:
      - "80:80"
    networks:
      - magentoworld
    volumes:
      - ./etc:/var/www/html/magento/app/etc
#      - ./src/Paylink:/var/www/html/magento/app/code/CityPay/Paylink
#      - ./rootcomposer2.json:/var/www/html/magento/composer.json
      - ./src/cronjobcaller.php:/var/www/html/magento/pub/cronjobcaller.php
    links:
      - mysql
    tty: true
    stdin_open: true
  mysql:
    image: mariadb:10
    container_name: citypay-magento-mysql
    restart: "no"
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
    networks:
      - magentoworld
    volumes:
      - ./config:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
networks:
  magentoworld:
    driver: bridge

volumes:
  magento2generated: