user  nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events { worker_connections 1024; }

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  sendfile on;
  keepalive_timeout 65;

  # Map the forwarded proto to HTTPS=on|off
  map $http_x_forwarded_proto $fe_https {
    default off;
    https   on;
  }

  # Map HTTPS flag to the port we pass to PHP
  map $fe_https $fe_port {
    on      443;
    default 80;
  }

  include /etc/nginx/conf.d/*.conf;
}